import { chmodSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

export interface ShimOptions {
	/** Directory that will be added to PATH. */
	binDir: string;
	/** Absolute path to the node executable to use (the runner's own node). */
	nodePath: string;
	/** Absolute path to cli.mjs. */
	cliPath: string;
}

const shq = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;

export function shimSources(opts: ShimOptions): { posix: string; cmd: string } {
	const posix = [
		'#!/bin/sh',
		'# generated by kjanat/actions-shells — do not edit',
		`exec ${shq(opts.nodePath)} ${shq(opts.cliPath)} "$@"`,
		'',
	].join('\n');
	const cmd = [
		'@echo off',
		'rem generated by kjanat/actions-shells - do not edit',
		`"${opts.nodePath}" "${opts.cliPath}" %*`,
		'',
	].join('\r\n');
	return { posix, cmd };
}

export const SHIM_NAMES = ['actions-shell', 'actions-shells'] as const;

/** Write `<name>` and `<name>.cmd` for every shim name into binDir. Returns the paths written. */
export function writeShims(opts: ShimOptions): string[] {
	mkdirSync(opts.binDir, { recursive: true });
	const { posix, cmd } = shimSources(opts);
	const written: string[] = [];
	for (const name of SHIM_NAMES) {
		const posixPath = path.join(opts.binDir, name);
		const cmdPath = path.join(opts.binDir, `${name}.cmd`);
		writeFileSync(posixPath, posix, { mode: 0o755 });
		try {
			chmodSync(posixPath, 0o755);
		} catch {
			/* windows */
		}
		writeFileSync(cmdPath, cmd);
		written.push(posixPath, cmdPath);
	}
	return written;
}
